apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.backend.configMapName}}
  namespace: {{.Values.global.namespace}}
data:
  DB_HOST: tasks-db-svc
  DB_PORT: "5432"
  CORS_ALLOWED_ORIGINS: "http://tasks-app.local,http://10.50.51.11,http://localhost:5173"
  ALLOWED_HOSTS: "tasks-app.local,api-tasks.local,api-tasks.local:8000,10.50.51.11,localhost,127.0.0.1"
  DEBUG: "False"
