apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.serviceName}}
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.backend.name}}
  ports:
    - port: 8000
      targetPort: 8000