apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.frontend.name}}
  namespace: {{.Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.frontend.name}}
  template:
    metadata:
      labels:
        app: {{.Values.frontend.name}}
    spec:
      containers:
        - name: {{.Values.frontend.name}}
          image: "{{ .Values.global.registry}}/{{.Values.frontend.image.repository}}:{{.Values.frontend.image.tag}}"
          imagePullPolicy: Always
          valueFrom:
            - configMapKeyRef:
                name: {{.Values.frontend.configMapName}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
