apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-app-ingress
  namespace: {{.Values.frontend.namespace}}
  labels:
    app.kubernetes.io/name: frontend-app-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.priority: "10000"
    traefik.ingress.kubernetes.io/router.pathmatcher: "PathPrefix"
spec:
  rules:
    - host: tasks-app.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{.Values.frontend.serviceName}}
                port:
                  number: 80
