apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend_tasks_app.serviceName}}
  namespace: {{.Values.frontend_tasks_app.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.frontend_tasks_app.name}}
  ports:
    - port: 80
      targetPort: 8080