name: "Backend-Tasks-App"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

defaults:
  run:
    working-directory: backend

jobs:
  linting:
    name: Linters code
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up virtual environment and install linters
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install black flake8
      - name: Black
        run: |
          ./venv/bin/black --check .
      - name: Flake8
        run: |
          ./venv/bin/flake8 .
          
  testing:
    name: Testing code
    runs-on: self-hosted
    needs: linting

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
      - name: Run Tests
        env:
          DB_HOST: postgres
          DB_PORT: 5432
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USER: ${{ vars.DB_USER }}
        run: |
          ./venv/bin/python manage.py migrate
          ./venv/bin/python manage.py test
