name: "Backend-Tasks-App"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
defaults:
  run:
    working-directory: backend

jobs:
  linting:
    name: Linters code
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up virtual environment and install linters
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install flake8
      - name: Flake8
        run: |
          ./venv/bin/flake8 .

  testing:
    name: Testing code
    runs-on: self-hosted
    needs: linting

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ vars.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USER: ${{ vars.DB_USER }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ./venv/bin/python manage.py migrate
          ./venv/bin/pytest
  build-scanning-push:
    name: Build, Scanning and Push Image
    runs-on: self-hosted
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          load: true
          tags: |
            ${{vars.HARBOR_REGISTRY}}/backend-django-tasks/backend-django-tasks:${{ github.sha }}
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{vars.HARBOR_REGISTRY}}/backend-django-tasks/backend-django-tasks:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: Login to Harbor Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Push image to Harbor
        run: |
          docker push \
            ${{ vars.HARBOR_REGISTRY }}/backend-django-tasks/backend-django-tasks:${{ github.sha }}
  update-manifest:
    name: Update Helm image tag
    runs-on: self-hosted
    needs: build-scanning-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update backend image tag
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.backend.image.tag = "${{ github.sha }}"' helm/values.yaml
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add helm/values.yaml
          git commit -m "chore(backend): update image to ${{ github.sha }}" || exit 0

      - name: Show changes
        run: |
          git diff -- helm/values.yaml
